// const List<DropdownMenuItem<String>> regionOptionsDropdownItem = [
//     DropdownMenuItem(value: "Bahrain", child: Text("Bahrain")),
//     DropdownMenuItem(value: "Egypt", child: Text("Egypt")),
//     DropdownMenuItem(value: "Iran", child: Text("Iran")),
//     DropdownMenuItem(value: "Iraq", child: Text("Iraq")),
//     DropdownMenuItem(value: "Jordan", child: Text("Jordan")),
//     DropdownMenuItem(value: "Kuwait", child: Text("Kuwait")),
//     DropdownMenuItem(value: "Lebanon", child: Text("Lebanon")),
//     DropdownMenuItem(value: "Libya", child: Text("Libya")),
//     DropdownMenuItem(value: "Mauritania", child: Text("Mauritania")),
//     DropdownMenuItem(value: "Oman", child: Text("Oman")),
//     DropdownMenuItem(value: "Palestine", child: Text("Palestine")),
//     DropdownMenuItem(value: "Qatar", child: Text("Qatar")),
//     DropdownMenuItem(value: "Saudi Arabia", child: Text("Saudi Arabia")),
//     DropdownMenuItem(value: "Sudan", child: Text("Sudan")),
//     DropdownMenuItem(value: "Syria", child: Text("Syria")),
//     DropdownMenuItem(value: "Tunisia", child: Text("Tunisia")),
//     DropdownMenuItem(
//         value: "United Arab Emirates", child: Text("United Arab Emirates")),
//     DropdownMenuItem(value: "Yemen", child: Text("Yemen")),
//     DropdownMenuItem(value: "Morocco", child: Text("Morocco")),
//     DropdownMenuItem(value: "Algeria", child: Text("Algeria")),
//   ];

const List<String> regionOptionsString = [
  "Bahrain",
  "Egypt",
  "Iran",
  "Iraq",
  "Jordan",
  "Kuwait",
  "Lebanon",
  "Libya",
  "Mauritania",
  "Oman",
  "Palestine",
  "Qatar",
  "Saudi Arabia",
  "Sudan",
  "Syria",
  "Tunisia",
  "United Arab Emirates",
  "Yemen",
  "Morocco",
  "Algeria",
];
